'use client'

import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import { store } from "../store/store.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    window.__STORE__ = store
  }, [])
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
